### ISSUE TITLE
Support for images in signature - upload

### ISSUE THREAD

**Issue by asktheo** [birdlifedk/visitkort-app#1]
See post: https://www.campaignmonitor.com/blog/email-marketing/2013/02/embedded-images-in-html-email/
Microsoft has removed support for embedded images in Outlook 2007+. 
This means we should develop an upload feature for images. 
In the upload sequence Java imageIO handling should control the size of image (logo).

**Comment by DOFandersolsen** [comment]
Images will be hardcoded into the signatures.

No longer applicable
